# Generated by Django 5.0.3 on 2024-03-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_status',
        ),
        migrations.AlterField(
            model_name='employee',
            name='administration',
            field=models.CharField(choices=[('admin1', 'Administration 1'), ('admin2', 'Administration 2'), ('admin3', 'Administration 3')], max_length=50, verbose_name='Administration'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='base_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Base Salary'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='branch',
            field=models.CharField(choices=[('branch1', 'Branch 1'), ('branch2', 'Branch 2'), ('branch3', 'Branch 3')], max_length=50, verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Contract Expiry Date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fingerprint_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Fingerprint Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Insurance Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='insurance_subscription_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Insurance Subscription Fee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(verbose_name='Joining Date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name_in_english',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name in English'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='national_id',
            field=models.CharField(max_length=20, verbose_name='National ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='period_of_work',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract')], max_length=20, verbose_name='Period of Work'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='section',
            field=models.CharField(blank=True, choices=[('section1', 'Section 1'), ('section2', 'Section 2'), ('section3', 'Section 3')], max_length=50, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='subject_to_tax',
            field=models.BooleanField(default=False, verbose_name='Subject to Tax'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='subscribed_to_insurance',
            field=models.BooleanField(default=False, verbose_name='Subscribed to Insurance'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='title',
            field=models.CharField(choices=[('title1', 'Title 1'), ('title2', 'Title 2'), ('title3', 'Title 3')], max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_system',
            field=models.CharField(choices=[('system1', 'System 1'), ('system2', 'System 2'), ('system3', 'System 3')], max_length=20, verbose_name='Work System'),
        ),
    ]
